framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - 'assets/'
            - 'var/tailwind/'
        excluded_patterns:
            - '*/assets/styles/**/*.scss'
