framework:
    default_locale: '%env(APP_LANG_DEFAULT%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['%env(APP_LANG_OTHERS)%']
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
